version: "2"
services:
  react-spotify:
    # image: friendlyngeeks/peons-rpi:latest
    container_name: react-spotify
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 7007:7007 # These parameters are separated by a colon and indicate <external>:<internal> respectively.
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    network_mode: host # console shows device ip HOST
